import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Relogio from "@/components/Relogio/Relogio";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (


    <html lang="en">
      <body
        className="
        flex
        flex-col
        justify-center
        items-center
        min-h-screen
        
        "
      >

        <header>
          <h1>React 💕 Next.js</h1>

          <nav className="flex gap-4">
            <Link href="/">Home</Link>
            <Link href="/route">Route</Link>
            <Link href="/caracteristicas">Caracteristicas</Link>
            <Link href="/projetos">Projetos</Link>
            <Link href="/contador">Contador</Link>
            <Link href="/loja">Loja</Link>
          </nav>

        </header>


        <main className="
        bg-purple-400
        w-[70vw]
        m-3
        p-3
        min-h-[90vw]
        rounded-xl
        ">
          {children}
        </main>

        <footer className="
        w-[70vw]
        m-3
        p-3
        rounded-xl"><Relogio></Relogio></footer>

      </body>
    </html>


  );


}
